-- This migration inserts missing car models and variants using brand/model lookups.
-- It avoids hard-coded model UUIDs, so it works on any database where brands exist.

WITH new_variants (brand_name, model_name, variant_name, is_active) AS (
  ('Toyota', 'Allion', 'A15', true),
  ('Toyota', 'Allion', 'A18', true),
  ('Toyota', 'Allion', 'A20', true),
  ('Toyota', 'Allion', 'G Package', true),
  ('Toyota', 'Axio', '1.3 X', true),
  ('Toyota', 'Axio', '1.5 G', true),
  ('Toyota', 'Axio', 'Hybrid', true),
  ('Toyota', 'Axio', '1.5 GT', true),
  ('Toyota', 'Premio', 'F EX', true),
  ('Toyota', 'Premio', 'G EX', true),
  ('Toyota', 'Premio', '1.8 G', true),
  ('Toyota', 'Premio', '2.0 G', true),
  ('Toyota', 'Fielder', 'X', true),
  ('Toyota', 'Fielder', 'S', true),
  ('Toyota', 'Fielder', 'G', true),
  ('Toyota', 'Fielder', 'Hybrid', true),
  ('Toyota', 'Belta', 'X', true),
  ('Toyota', 'Belta', 'G', true),
  ('Toyota', 'Belta', '1.0 X', true),
  ('Toyota', 'Belta', '1.3 G', true),
  ('Toyota', 'Passo', 'X', true),
  ('Toyota', 'Passo', 'G', true),
  ('Toyota', 'Passo', 'Plus Hana', true),
  ('Toyota', 'Passo', 'Moda', true),
  ('Toyota', 'Auris', '150X', true),
  ('Toyota', 'Auris', '180G', true),
  ('Toyota', 'Auris', 'Hybrid', true),
  ('Toyota', 'Auris', 'RS', true),
  ('Toyota', 'Corolla Cross', 'Z', true),
  ('Toyota', 'Corolla Cross', 'S', true),
  ('Toyota', 'Corolla Cross', 'G', true),
  ('Toyota', 'Corolla Cross', 'Hybrid Z', true),
  ('Toyota', 'Raize', 'Z', true),
  ('Toyota', 'Raize', 'G', true),
  ('Toyota', 'Raize', 'X', true),
  ('Toyota', 'Raize', 'Turbo Z', true),
  ('Toyota', 'Yaris Cross', 'G', true),
  ('Toyota', 'Yaris Cross', 'Z', true),
  ('Toyota', 'Yaris Cross', 'Hybrid G', true),
  ('Toyota', 'Yaris Cross', 'GR Sport', true),
  ('Toyota', 'Innova', 'G', true),
  ('Toyota', 'Innova', 'V', true),
  ('Toyota', 'Innova', 'E', true),
  ('Toyota', 'Innova', 'Zenix Hybrid', true),
  ('Toyota', 'Avanza', 'G', true),
  ('Toyota', 'Avanza', 'S', true),
  ('Toyota', 'Avanza', 'E', true),
  ('Toyota', 'Avanza', '1.3 MT', true),
  ('Toyota', 'Rush', 'S', true),
  ('Toyota', 'Rush', 'G', true),
  ('Toyota', 'Rush', 'TRD Sportivo', true),
  ('Toyota', 'Voxy', 'ZS', true),
  ('Toyota', 'Voxy', 'ZS Kirameki', true),
  ('Toyota', 'Voxy', 'V', true),
  ('Toyota', 'Voxy', 'Hybrid ZS', true),
  ('Toyota', 'Esquire', 'Gi', true),
  ('Toyota', 'Esquire', 'Xi', true),
  ('Toyota', 'Esquire', 'Hybrid Gi', true),
  ('Toyota', 'Esquire', 'Hybrid Xi', true),
  ('Toyota', 'Estima', 'X', true),
  ('Toyota', 'Estima', 'G', true),
  ('Toyota', 'Estima', 'Aeras', true),
  ('Toyota', 'Estima', 'Hybrid G', true),
  ('Toyota', 'Crown', '2.0 RS', true),
  ('Toyota', 'Crown', '2.5 RS Advance', true),
  ('Toyota', 'Crown', 'Hybrid', true),
  ('Toyota', 'Crown', 'Athlete', true),
  ('Toyota', 'Markhor', '1.3 MT', true),
  ('Toyota', 'Markhor', '1.3 CVT', true),
  ('Toyota', 'Probox', 'DX', true),
  ('Toyota', 'Probox', 'GL', true),
  ('Toyota', 'Probox', 'F Extra Package', true),
  ('Toyota', 'Porte', 'X', true),
  ('Toyota', 'Porte', 'G', true),
  ('Toyota', 'Porte', '130i', true),
  ('Toyota', 'Spade', 'F', true),
  ('Toyota', 'Spade', 'G', true),
  ('Toyota', 'Spade', 'Hybrid', true),
  ('Toyota', 'Sienta', 'X', true),
  ('Toyota', 'Sienta', 'G', true),
  ('Toyota', 'Sienta', 'Hybrid G', true),
  ('Toyota', 'Sienta', 'Funbase', true),
  ('Toyota', 'Roomy', 'G', true),
  ('Toyota', 'Roomy', 'X', true),
  ('Toyota', 'Roomy', 'Custom G', true),
  ('Toyota', 'Roomy', 'Custom Z', true),
  ('Toyota', 'Tank', 'G', true),
  ('Toyota', 'Tank', 'X', true),
  ('Toyota', 'Tank', 'Custom G', true),
  ('Toyota', 'Tank', 'Custom Z', true),
  ('Toyota', 'Town Ace', 'DX', true),
  ('Toyota', 'Town Ace', 'GL', true),
  ('Toyota', 'Town Ace', 'Van DX', true),
  ('Toyota', 'FJ Cruiser', 'Base 4WD', true),
  ('Toyota', 'FJ Cruiser', 'Trail Teams', true),
  ('Toyota', 'FJ Cruiser', 'Ultimate Edition', true),
  ('Toyota', 'Revo (Hilux Revo)', 'G', true),
  ('Toyota', 'Revo (Hilux Revo)', 'E', true),
  ('Toyota', 'Revo (Hilux Revo)', 'J', true),
  ('Toyota', 'Revo (Hilux Revo)', 'Z GD', true),
  ('Toyota', 'Revo (Hilux Revo)', 'Smart Cab', true),
  ('Toyota', 'Grandia', 'GL', true),
  ('Toyota', 'Grandia', 'Super GL', true),
  ('Toyota', 'Grandia', 'Commuter', true),
  ('Toyota', '86', 'GT', true),
  ('Toyota', '86', 'GR Sport', true),
  ('Toyota', '86', 'GTS', true),
  ('Toyota', 'Wish', 'X', true),
  ('Toyota', 'Wish', 'Z', true),
  ('Toyota', 'Wish', 'S', true),
  ('Toyota', 'Wish', '1.8 G', true),
  ('Honda', 'Life (Kei)', 'C', true),
  ('Honda', 'Life (Kei)', 'G', true),
  ('Honda', 'Life (Kei)', 'Diva', true),
  ('Honda', 'Life (Kei)', 'Turbo', true),
  ('Honda', 'Shuttle', 'X', true),
  ('Honda', 'Shuttle', 'Hybrid X', true),
  ('Honda', 'Shuttle', 'Hybrid Z', true),
  ('Honda', 'Grace', 'LX', true),
  ('Honda', 'Grace', 'Hybrid', true),
  ('Honda', 'Grace', 'EX', true),
  ('Honda', 'Jade', 'FF', true),
  ('Honda', 'Jade', 'RS Hybrid', true),
  ('Honda', 'Jade', 'Hybrid', true),
  ('Honda', 'Stepwgn', 'G', true),
  ('Honda', 'Stepwgn', 'Spada', true),
  ('Honda', 'Stepwgn', 'AIR', true),
  ('Honda', 'Stepwgn', 'Spada Hybrid', true),
  ('Honda', 'Elysion', 'G', true),
  ('Honda', 'Elysion', 'VG', true),
  ('Honda', 'Elysion', 'Prestige', true),
  ('Honda', 'Odyssey', 'L', true),
  ('Honda', 'Odyssey', 'Absolute', true),
  ('Honda', 'Odyssey', 'EX', true),
  ('Honda', 'Odyssey', 'Hybrid Absolute', true),
  ('Honda', 'Mobilio', 'G', true),
  ('Honda', 'Mobilio', 'RS', true),
  ('Honda', 'Mobilio', 'E', true),
  ('Honda', 'N-One', 'G', true),
  ('Honda', 'N-One', 'G L Package', true),
  ('Honda', 'N-One', 'RS', true),
  ('Honda', 'N-WGN', 'G', true),
  ('Honda', 'N-WGN', 'Custom G', true),
  ('Honda', 'N-WGN', 'Custom L', true),
  ('Honda', 'N-WGN', 'Turbo', true),
  ('Honda', 'WR-V', 'SV', true),
  ('Honda', 'WR-V', 'EX', true),
  ('Honda', 'WR-V', 'VX', true),
  ('Honda', 'ZR-V', 'Z', true),
  ('Honda', 'ZR-V', 'X', true),
  ('Honda', 'ZR-V', 'e:HEV Z', true),
  ('Honda', 'Type R', 'FK8', true),
  ('Honda', 'Type R', 'FL5', true),
  ('Honda', 'Type R', 'DC5', true),
  ('Hyundai', 'Sonata', 'GL', true),
  ('Hyundai', 'Sonata', 'GLS', true),
  ('Hyundai', 'Sonata', 'Sport 2.5T', true),
  ('Hyundai', 'Sonata', 'Hybrid', true),
  ('Hyundai', 'Santa Fe', 'GLS', true),
  ('Hyundai', 'Santa Fe', 'Luxury', true),
  ('Hyundai', 'Santa Fe', 'Ultimate', true),
  ('Hyundai', 'Santa Fe', 'Plug-in Hybrid', true),
  ('Hyundai', 'Creta', 'GL', true),
  ('Hyundai', 'Creta', 'GLX', true),
  ('Hyundai', 'Creta', 'GLS', true),
  ('Hyundai', 'Creta', 'Executive', true),
  ('Hyundai', 'Palisade', 'SEL', true),
  ('Hyundai', 'Palisade', 'Limited', true),
  ('Hyundai', 'Palisade', 'Calligraphy', true),
  ('Hyundai', 'Venue', 'S', true),
  ('Hyundai', 'Venue', 'SX', true),
  ('Hyundai', 'Venue', 'SX(O)', true),
  ('Hyundai', 'i10', 'Era', true),
  ('Hyundai', 'i10', 'Magna', true),
  ('Hyundai', 'i10', 'Sportz', true),
  ('Hyundai', 'i20', 'Era', true),
  ('Hyundai', 'i20', 'Magna', true),
  ('Hyundai', 'i20', 'Sportz', true),
  ('Hyundai', 'i20', 'Asta', true),
  ('Hyundai', 'Ioniq 5', 'Standard Range RWD', true),
  ('Hyundai', 'Ioniq 5', 'Long Range RWD', true),
  ('Hyundai', 'Ioniq 5', 'Long Range AWD', true),
  ('Suzuki', 'Mehran', 'VX', true),
  ('Suzuki', 'Mehran', 'VXR', true),
  ('Suzuki', 'Mehran', 'Euro II', true),
  ('Suzuki', 'Every', 'PA', true),
  ('Suzuki', 'Every', 'PC', true),
  ('Suzuki', 'Every', 'Join', true),
  ('Suzuki', 'Every', 'Wagon', true),
  ('Suzuki', 'Carry', 'ST90', true),
  ('Suzuki', 'Carry', 'DB52T', true),
  ('Suzuki', 'Carry', 'Wide Cab', true),
  ('Suzuki', 'Ravi', 'Standard', true),
  ('Suzuki', 'Ravi', 'Euro II', true),
  ('Suzuki', 'Ravi', 'CNG', true),
  ('Suzuki', 'Ertiga', 'GL', true),
  ('Suzuki', 'Ertiga', 'GLX', true),
  ('Suzuki', 'Ertiga', 'GX', true),
  ('Suzuki', 'Ertiga', 'Dreza', true),
  ('Suzuki', 'Liana', 'RXi', true),
  ('Suzuki', 'Liana', 'LXi', true),
  ('Suzuki', 'Liana', 'GLX', true),
  ('Suzuki', 'Hustler', 'G', true),
  ('Suzuki', 'Hustler', 'J Turbo', true),
  ('Suzuki', 'Hustler', 'Hybrid X', true),
  ('Suzuki', 'Hustler', 'Hybrid G Turbo', true),
  ('Suzuki', 'Spacia', 'G', true),
  ('Suzuki', 'Spacia', 'Custom Z Turbo', true),
  ('Suzuki', 'Spacia', 'Hybrid G', true),
  ('Suzuki', 'Spacia', 'Hybrid Custom Z', true),
  ('Suzuki', 'Vitara', 'GL', true),
  ('Suzuki', 'Vitara', 'GLX', true),
  ('Suzuki', 'Vitara', 'S Turbo', true),
  ('Suzuki', 'Vitara', 'AllGrip', true),
  ('Suzuki', 'Ignis', 'A', true),
  ('Suzuki', 'Ignis', 'MX', true),
  ('Suzuki', 'Ignis', 'Hybrid MX', true),
  ('Suzuki', 'XL7', 'Alpha', true),
  ('Suzuki', 'XL7', 'Zeta', true),
  ('Suzuki', 'XL7', 'Beta', true),
  ('Suzuki', 'SX4', 'GL', true),
  ('Suzuki', 'SX4', 'GLX', true),
  ('Suzuki', 'SX4', 'S-Cross', true),
  ('Suzuki', 'APV', 'GL', true),
  ('Suzuki', 'APV', 'Arena', true),
  ('Suzuki', 'APV', 'Luxury', true),
  ('Suzuki', 'Lapin', 'G', true),
  ('Suzuki', 'Lapin', 'Chocolate', true),
  ('Suzuki', 'Lapin', 'SS Turbo', true),
  ('Suzuki', 'Solio', 'G', true),
  ('Suzuki', 'Solio', 'Bandit Hybrid MV', true),
  ('Suzuki', 'Solio', 'Hybrid MX', true),
  ('Suzuki', 'MR Wagon', 'E', true),
  ('Suzuki', 'MR Wagon', 'G', true),
  ('Suzuki', 'MR Wagon', 'Wit TS Turbo', true),
  ('Suzuki', 'Palette', 'G', true),
  ('Suzuki', 'Palette', 'SW', true),
  ('Suzuki', 'Palette', 'SW Turbo', true),
  ('Suzuki', 'Super Carry', 'Pickup', true),
  ('Suzuki', 'Super Carry', 'Minivan', true),
  ('Nissan', 'Serena', 'S-Hybrid', true),
  ('Nissan', 'Serena', 'Highway Star', true),
  ('Nissan', 'Serena', 'Rider', true),
  ('Nissan', 'Serena', 'e-POWER', true),
  ('Nissan', 'Sylphy', 'Base', true),
  ('Nissan', 'Sylphy', 'S', true),
  ('Nissan', 'Sylphy', 'SV', true),
  ('Nissan', 'Sylphy', 'e-POWER', true),
  ('Nissan', 'Tiida', '1.6 S', true),
  ('Nissan', 'Tiida', '1.8 SL', true),
  ('Nissan', 'Tiida', 'Hatchback', true),
  ('Nissan', 'Teana', '2.0 XL', true),
  ('Nissan', 'Teana', '2.5 XL', true),
  ('Nissan', 'Teana', '3.5 XL', true),
  ('Nissan', 'Murano', 'S', true),
  ('Nissan', 'Murano', 'SV', true),
  ('Nissan', 'Murano', 'Platinum', true),
  ('Nissan', 'Elgrand', 'E51', true),
  ('Nissan', 'Elgrand', 'E52', true),
  ('Nissan', 'Elgrand', 'Highway Star', true),
  ('Nissan', 'Elgrand', 'Rider', true),
  ('Nissan', 'Moco', 'E', true),
  ('Nissan', 'Moco', 'S', true),
  ('Nissan', 'Moco', 'X Turbo', true),
  ('Nissan', 'Dayz', 'X', true),
  ('Nissan', 'Dayz', 'Highway Star', true),
  ('Nissan', 'Dayz', 'Rider', true),
  ('Nissan', 'Bluebird', 'S', true),
  ('Nissan', 'Bluebird', 'SLX', true),
  ('Nissan', 'Bluebird', 'G18', true),
  ('Nissan', 'Leaf', '40 kWh', true),
  ('Nissan', 'Leaf', '62 kWh e+', true),
  ('Nissan', 'Leaf', 'G', true),
  ('Nissan', 'Presage', 'S', true),
  ('Nissan', 'Presage', 'Rider', true),
  ('Nissan', 'Presage', '3.5 V6', true),
  ('Nissan', 'Caravan', 'VX', true),
  ('Nissan', 'Caravan', 'GX', true),
  ('Nissan', 'Caravan', 'Diesel', true),
  ('Mitsubishi', 'Pajero Mini', 'VR', true),
  ('Mitsubishi', 'Pajero Mini', 'Active Field Edition', true),
  ('Mitsubishi', 'Pajero Mini', 'Turbo', true),
  ('Mitsubishi', 'eK Wagon', 'G', true),
  ('Mitsubishi', 'eK Wagon', 'Custom G', true),
  ('Mitsubishi', 'eK Wagon', 'T Turbo', true),
  ('Mitsubishi', 'eK Space', 'G', true),
  ('Mitsubishi', 'eK Space', 'Custom G', true),
  ('Mitsubishi', 'eK Space', 'Custom T Turbo', true),
  ('Mitsubishi', 'Mirage', 'GLX', true),
  ('Mitsubishi', 'Mirage', 'GLS', true),
  ('Mitsubishi', 'Mirage', 'G4 GLX', true),
  ('Mitsubishi', 'Attrage', 'GLX', true),
  ('Mitsubishi', 'Attrage', 'GLS', true),
  ('Mitsubishi', 'Attrage', 'Premium', true),
  ('Mitsubishi', 'ASX', 'GLS', true),
  ('Mitsubishi', 'ASX', 'GLX 4WD', true),
  ('Mitsubishi', 'ASX', 'Exceed 4WD', true),
  ('Mitsubishi', 'Eclipse Cross', 'M', true),
  ('Mitsubishi', 'Eclipse Cross', 'G 4WD', true),
  ('Mitsubishi', 'Eclipse Cross', 'P-HEV', true),
  ('Mitsubishi', 'Triton', 'GL', true),
  ('Mitsubishi', 'Triton', 'GLS', true),
  ('Mitsubishi', 'Triton', 'Ultimate', true),
  ('Mitsubishi', 'Triton', 'L200', true),
  ('Mitsubishi', 'Delica D5', 'G Power Package', true),
  ('Mitsubishi', 'Delica D5', 'D Power Package', true),
  ('Mitsubishi', 'Delica D5', 'P Value Package', true),
  ('Mitsubishi', 'L200', 'Standard', true),
  ('Mitsubishi', 'L200', 'Club Cab', true),
  ('Mitsubishi', 'L200', 'Double Cab', true),
  ('MG', '360', 'Comfort', true),
  ('MG', '360', 'Luxury', true),
  ('MG', '360', 'Trophy', true),
  ('MG', '3', 'S', true),
  ('MG', '3', 'Exclusive', true),
  ('MG', '3', 'X', true),
  ('MG', '5', 'Standard', true),
  ('MG', '5', 'Comfort', true),
  ('MG', '5', 'Luxury', true),
  ('MG', 'GT', 'Comfort', true),
  ('MG', 'GT', 'Luxury', true),
  ('MG', 'GT', 'Trophy', true),
  ('MG', 'GS', 'Comfort', true),
  ('MG', 'GS', 'Luxury', true),
  ('MG', 'GS', 'Trophy', true),
  ('MG', 'RX5', 'Comfort', true),
  ('MG', 'RX5', 'Luxury', true),
  ('MG', 'RX5', 'Trophy', true),
  ('MG', 'MG4', 'Standard', true),
  ('MG', 'MG4', 'Luxury', true),
  ('MG', 'MG4', 'Trophy', true),
  ('Changan', 'CS55 Plus', 'MT', true),
  ('Changan', 'CS55 Plus', 'CVT', true),
  ('Changan', 'CS55 Plus', 'PHEV', true),
  ('Changan', 'Uni-K', '2.0T', true),
  ('Changan', 'Uni-K', '2.0T iDD', true),
  ('Changan', 'Uni-K', 'Ultra', true),
  ('Changan', 'Uni-V', '1.5T MT', true),
  ('Changan', 'Uni-V', '1.5T CVT', true),
  ('Changan', 'Uni-V', 'Ultra', true),
  ('Changan', 'Hunter', '4x4 Luxury', true),
  ('Changan', 'Hunter', '4x4 Premium', true),
  ('Changan', 'Hunter', 'Comfort', true),
  ('Changan', 'Lumin', 'Comfort', true),
  ('Changan', 'Lumin', 'Luxury', true),
  ('Changan', 'Lumin', 'S', true),
  ('Changan', 'Eado Plus', '1.4T Comfort', true),
  ('Changan', 'Eado Plus', '1.4T Luxury', true),
  ('Changan', 'Eado Plus', '1.4T Premium', true),
  ('DFSK', 'Glory 580', '1.5T MT', true),
  ('DFSK', 'Glory 580', '1.5T CVT', true),
  ('DFSK', 'Glory 580', '1.5T Pro', true),
  ('DFSK', 'Glory 500', 'MT', true),
  ('DFSK', 'Glory 500', 'CVT', true),
  ('DFSK', 'Glory 330', 'MT', true),
  ('DFSK', 'Glory 330', 'CVT', true),
  ('DFSK', 'K07', 'Standard', true),
  ('DFSK', 'K07', 'Long Wheel', true),
  ('DFSK', 'Star V', 'Comfort', true),
  ('DFSK', 'Star V', 'Luxury', true),
  ('DFSK', 'Sokon', 'Standard', true),
  ('DFSK', 'Sokon', 'Cargo', true),
  ('Haval', 'H1', 'Comfort', true),
  ('Haval', 'H1', 'Luxury', true),
  ('Haval', 'H1', 'Blue Label', true),
  ('Haval', 'H2', 'City', true),
  ('Haval', 'H2', 'Elite', true),
  ('Haval', 'H2', 'Luxury', true),
  ('Haval', 'H4', 'Blue Label', true),
  ('Haval', 'H4', 'Red Label', true),
  ('Haval', 'H5', 'City', true),
  ('Haval', 'H5', 'Elite', true),
  ('Haval', 'H5', 'Adventure', true),
  ('Haval', 'F7', 'Comfort', true),
  ('Haval', 'F7', 'Luxury', true),
  ('Haval', 'F7', 'Supreme', true),
  ('Haval', 'Dargo', 'Comfort', true),
  ('Haval', 'Dargo', 'Luxury', true),
  ('Haval', 'Dargo', 'PHEV', true),
  ('Proton', 'X70', 'Standard', true),
  ('Proton', 'X70', 'Executive', true),
  ('Proton', 'X70', 'Premium', true),
  ('Proton', 'X70', 'TGDi', true),
  ('Proton', 'Persona', 'Standard', true),
  ('Proton', 'Persona', 'Executive', true),
  ('Proton', 'Persona', 'Premium', true),
  ('Proton', 'Exora', 'Standard', true),
  ('Proton', 'Exora', 'Executive', true),
  ('Proton', 'Exora', 'Premium Turbo', true),
  ('Audi', 'A3', '35 TFSI', true),
  ('Audi', 'A3', '40 TFSI', true),
  ('Audi', 'A3', 'S3 Sportback', true),
  ('Audi', 'A3', 'RS3', true),
  ('Audi', 'A4', '35 TFSI', true),
  ('Audi', 'A4', '40 TFSI', true),
  ('Audi', 'A4', '45 TFSI', true),
  ('Audi', 'A4', 'S4', true),
  ('Audi', 'A5', '40 TFSI', true),
  ('Audi', 'A5', '45 TFSI', true),
  ('Audi', 'A5', 'S5', true),
  ('Audi', 'A5', 'RS5', true),
  ('Audi', 'A6', '45 TFSI', true),
  ('Audi', 'A6', '55 TFSI', true),
  ('Audi', 'A6', 'S6', true),
  ('Audi', 'A6', '40 TDI', true),
  ('Audi', 'Q3', '35 TFSI', true),
  ('Audi', 'Q3', '40 TFSI', true),
  ('Audi', 'Q3', 'RS Q3', true),
  ('Audi', 'Q5', '40 TFSI', true),
  ('Audi', 'Q5', '45 TFSI', true),
  ('Audi', 'Q5', 'SQ5', true),
  ('Audi', 'Q5', 'e TFSI PHEV', true),
  ('Audi', 'Q7', '45 TFSI', true),
  ('Audi', 'Q7', '55 TFSI', true),
  ('Audi', 'Q7', 'SQ7', true),
  ('Audi', 'Q8', '55 TFSI', true),
  ('Audi', 'Q8', 'SQ8', true),
  ('Audi', 'Q8', 'RS Q8', true),
  ('Audi', 'e-tron', '50 quattro', true),
  ('Audi', 'e-tron', '55 quattro', true),
  ('Audi', 'e-tron', 'S', true),
  ('BMW', '3 Series', '318i', true),
  ('BMW', '3 Series', '320i', true),
  ('BMW', '3 Series', '330i', true),
  ('BMW', '3 Series', 'M3', true),
  ('BMW', '3 Series', '320d', true),
  ('BMW', '5 Series', '520i', true),
  ('BMW', '5 Series', '530i', true),
  ('BMW', '5 Series', '540i', true),
  ('BMW', '5 Series', 'M5', true),
  ('BMW', '5 Series', '530e PHEV', true),
  ('BMW', '7 Series', '730i', true),
  ('BMW', '7 Series', '740i', true),
  ('BMW', '7 Series', '750i', true),
  ('BMW', '7 Series', 'M7', true),
  ('BMW', 'X3', 'xDrive20i', true),
  ('BMW', 'X3', 'xDrive30i', true),
  ('BMW', 'X3', 'M40i', true),
  ('BMW', 'X3', 'xDrive20d', true),
  ('BMW', 'X5', 'xDrive40i', true),
  ('BMW', 'X5', 'xDrive50i', true),
  ('BMW', 'X5', 'M50i', true),
  ('BMW', 'X5', 'xDrive45e PHEV', true),
  ('BMW', 'X6', 'xDrive40i', true),
  ('BMW', 'X6', 'M50i', true),
  ('BMW', 'X6', 'M Competition', true),
  ('BMW', 'X7', 'xDrive40i', true),
  ('BMW', 'X7', 'xDrive50i', true),
  ('BMW', 'X7', 'M60i', true),
  ('BMW', 'i4', 'eDrive35', true),
  ('BMW', 'i4', 'eDrive40', true),
  ('BMW', 'i4', 'xDrive40', true),
  ('BMW', 'i4', 'M50', true),
  ('BMW', 'iX', 'xDrive40', true),
  ('BMW', 'iX', 'xDrive50', true),
  ('BMW', 'iX', 'M60', true),
  ('Volkswagen', 'Golf', '1.4 TSI', true),
  ('Volkswagen', 'Golf', '2.0 TSI R-Line', true),
  ('Volkswagen', 'Golf', 'GTI', true),
  ('Volkswagen', 'Golf', 'R', true),
  ('Volkswagen', 'Polo', 'Trendline', true),
  ('Volkswagen', 'Polo', 'Comfortline', true),
  ('Volkswagen', 'Polo', 'Highline', true),
  ('Volkswagen', 'Polo', 'GTI', true),
  ('Volkswagen', 'Passat', '1.8T', true),
  ('Volkswagen', 'Passat', '2.0T', true),
  ('Volkswagen', 'Passat', '280 TSI', true),
  ('Volkswagen', 'Tiguan', 'Trendline', true),
  ('Volkswagen', 'Tiguan', 'Comfortline', true),
  ('Volkswagen', 'Tiguan', 'Highline', true),
  ('Volkswagen', 'Tiguan', 'R-Line', true),
  ('Volkswagen', 'Touareg', 'Elegance', true),
  ('Volkswagen', 'Touareg', 'R-Line', true),
  ('Volkswagen', 'Touareg', '3.0 V6 TSI', true),
  ('Prince', 'Pearl', 'CNG', true),
  ('Prince', 'Pearl', 'Petrol', true),
  ('Prince', 'DFSK Glory', '1.5T MT', true),
  ('Prince', 'DFSK Glory', '1.5T CVT', true),
  ('Prince', 'DFSK Glory', 'Pro', true),
  ('Prince', 'Carrier', 'Standard', true)
),
missing_models AS (
  SELECT DISTINCT b.id AS brand_id, nv.model_name AS name
  FROM new_variants nv
  JOIN public.car_brands b ON b.name = nv.brand_name
  LEFT JOIN public.car_models m ON m.brand_id = b.id AND m.name = nv.model_name
  WHERE m.id IS NULL
),
insert_models AS (
  INSERT INTO public.car_models (brand_id, name, is_active)
  SELECT brand_id, name, true FROM missing_models
  RETURNING id
)
INSERT INTO public.car_variants (model_id, name, is_active)
SELECT m.id, nv.variant_name, nv.is_active
FROM new_variants nv
JOIN public.car_brands b ON b.name = nv.brand_name
JOIN public.car_models m ON m.brand_id = b.id AND m.name = nv.model_name
ON CONFLICT (model_id, name) DO NOTHING;